# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian instead of
# Alpine to avoid DNS resolution issues in production.
#
# https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=ubuntu
# https://hub.docker.com/_/ubuntu?tab=tags
#
#
# This file is based on these images:
#
#   - https://hub.docker.com/r/hexpm/elixir/tags - for the build image
#   - https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-20221004-slim - for the release image
#   - https://pkgs.org/ - resource for finding needed packages
#   - Ex: hexpm/elixir:1.14.3-erlang-25.2-debian-bullseye-20221004-slim
#

ARG ELIXIR_VERSION=1.14.0
ARG OTP_VERSION=25.2.3
ARG UBUNTU_VERSION=jammy-20221130

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-ubuntu-${UBUNTU_VERSION}"
ARG RUNNER_IMAGE="ubuntu:${UBUNTU_VERSION}"

FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y \
  build-essential \
  git \
  pkg-config \
  libavutil-dev \
  libavcodec-dev

RUN apt-get install -y \
  libavformat-dev \
  clang-format \
  libssl-dev \
  autoconf \
  automake \
  clang-format \
  curl 

RUN apt-get install -y \
  libswscale-dev

RUN apt-get install -y \
  gcc-9 \
  git \
  libffi-dev \
  libglib2.0-dev \
  libncurses-dev \
  libreadline-dev \
  libssl-dev \
  libtool \
  libxslt-dev \
  libyaml-dev \
  locales \
  meson \
  ninja-build \
  unixodbc-dev \
  unzip \
  wget 

RUN apt-get install -y \
  libfdk-aac-dev

RUN apt-get install -y \
  libopus-dev

RUN apt-get install -y \
  libsrtp2-dev

RUN apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
  mix local.rebar --force

# set build ENV
ENV MIX_ENV="prod"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY lib lib

# Compile the release
RUN mix compile

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

COPY rel rel
RUN mix release

# start a new build stage so that the final image will only contain
# the compiled release and other runtime necessities
FROM ${RUNNER_IMAGE}

RUN apt-get update -y && apt-get install -y \
  build-essential \
  git \
  pkg-config \
  libavutil-dev \
  libavcodec-dev

RUN apt-get install -y \
  libavformat-dev \
  clang-format \
  libssl-dev \
  autoconf \
  automake \
  clang-format \
  curl 

RUN apt-get install -y \
  libswscale-dev

RUN apt-get install -y \
  gcc-9 \
  git \
  libffi-dev \
  libglib2.0-dev \
  libncurses-dev \
  libreadline-dev \
  libssl-dev \
  libtool \
  libxslt-dev \
  libyaml-dev \
  locales \
  meson \
  ninja-build \
  unixodbc-dev \
  unzip \
  wget 

RUN apt-get install -y \
  libfdk-aac-dev

RUN apt-get install -y \
  libopus-dev

RUN apt-get install -y \
  libsrtp2-dev

RUN apt-get clean && rm -f /var/lib/apt/lists/*_*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

# set runner ENV
ENV MIX_ENV="prod"
ENV SECRET_KEY_BASE=Ej4nG4p+bRGZ3/hCHEEADB/ePsKrfT6wGl1dfhDGR9vflfUSGyk9vcyu/uVmM7Jd

# Only copy the final release from the build stage
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/jellyfish ./

USER nobody

EXPOSE 4000

HEALTHCHECK CMD curl --fail http://localhost:4000 || exit 1  

CMD ["/app/bin/server"]

# Appended by flyctl
ENV ECTO_IPV6 true
ENV ERL_AFLAGS "-proto_dist inet6_tcp"
