# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian instead of
# Alpine to avoid DNS resolution issues in production.

ARG ELIXIR_VERSION=1.14.0
ARG OTP_VERSION=25.2.3
ARG UBUNTU_VERSION=jammy-20221130

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-ubuntu-${UBUNTU_VERSION}"
ARG RUNNER_IMAGE="ubuntu:${UBUNTU_VERSION}"

ARG MULTIMEDIA_LIBS="\
  ffmpeg \
  libssl-dev \
  libsrtp2-dev \
  libavutil-dev \
  libswscale-dev \
  libavcodec-dev \
  libfdk-aac-dev \
  libopus-dev \
  "

FROM ${BUILDER_IMAGE} as builder

ARG MULTIMEDIA_LIBS

# install build dependencies
RUN apt-get update -y && apt-get install -y \
  build-essential \
  git \
  pkg-config \
  ${MULTIMEDIA_LIBS} \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
  mix local.rebar --force

# set ENV for builder
ENV MIX_ENV="prod"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY lib lib

# Compile the release
RUN mix compile

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

COPY rel rel
RUN mix release

FROM ${RUNNER_IMAGE}

ARG MULTIMEDIA_LIBS

RUN apt-get update -y && apt-get install -y \
  build-essential \
  git \
  locales \ 
  pkg-config \
  ${MULTIMEDIA_LIBS} \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

# set runner ENV
ENV MIX_ENV="prod"
ENV SECRET_KEY_BASE=Ej4nG4p+bRGZ3/hCHEEADB/ePsKrfT6wGl1dfhDGR9vflfUSGyk9vcyu/uVmM7Jd

# Only copy the final release from the build stage
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/jellyfish ./

USER nobody

EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080 || exit 1  

CMD ["/app/bin/server"]

# Appended by flyctl
ENV ECTO_IPV6 true
ENV ERL_AFLAGS "-proto_dist inet6_tcp"
